import { auth, currentUser } from '@clerk/nextjs/server'
import { prisma } from './prisma'
import { headers } from 'next/headers'

/**
 * Resolve the current authenticated user from Clerk, and ensure we have
 * a matching Prisma User record for app-specific data (role, occupation, etc.).
 */
export async function getCurrentUser() {
  try {
    await headers() // Ensure headers are loaded for Clerk
    const { userId } = await auth()
    if (!userId) return null

    // Find existing local user linked to Clerk
    let user = await prisma.user.findUnique({ where: { clerkUserId: userId } })
    if (user) return user

    // First-time login: create local user record
    let cUser
    try {
      cUser = await currentUser()
    } catch (clerkError: any) {
      // Handle Clerk "Not Found" errors gracefully
      // This can happen if the user was deleted from Clerk but still has a session
      if (clerkError?.status === 404 || clerkError?.message?.includes('Not Found')) {
        console.warn('Clerk user not found, but session exists. User may have been deleted.')
        return null
      }
      throw clerkError
    }
    
    if (!cUser) return null

    const email = cUser.emailAddresses?.[0]?.emailAddress || 
                  cUser.primaryEmailAddress?.emailAddress || 
                  `clerk-${userId}@placeholder.local`

    // Prioritize username from Clerk, then firstName/lastName, then null
    let name: string | null = null
    if (cUser.username) {
      name = cUser.username
    } else if (cUser.firstName || cUser.lastName) {
      name = `${cUser.firstName || ''} ${cUser.lastName || ''}`.trim()
    }

    // Generate a unique key for the user (Prisma will auto-generate with @default(cuid()))
    // But we need to ensure it's set explicitly for compatibility
    try {
      user = await prisma.user.create({
        data: {
          clerkUserId: userId,
          email,
          name,
          role: 'user', // Default role, will be updated via API if role was selected
          // key will be auto-generated by Prisma with @default(cuid())
        },
      })
      return user
    } catch (createError: any) {
      // Handle unique constraint violations
      if (createError?.code === 'P2002') {
        // Check if it's email or clerkUserId conflict
        const meta = createError?.meta as any
        if (meta?.target?.includes('email')) {
          // User with this email already exists - try to link it to Clerk
          user = await prisma.user.findUnique({ where: { email } })
          if (user) {
            // Update existing user to link with Clerk if not already linked
            if (!user.clerkUserId) {
              user = await prisma.user.update({
                where: { id: user.id },
                data: { clerkUserId: userId },
              })
            }
            return user
          }
        } else if (meta?.target?.includes('clerkUserId')) {
          // User with this clerkUserId already exists - fetch it
        user = await prisma.user.findUnique({ where: { clerkUserId: userId } })
        if (user) return user
        }
      }
      throw createError
    }
  } catch (error) {
    console.error('getCurrentUser error:', error)
    return null
  }
}
